
db:
  endpoint: "PostgreSQL endpoint, ex: 127.0.0.1"
  user: "PostgreSQL username, ex: postgres"
  port: "PostgreSQL port, ex: 5432"
  db: "PostgreSQL database name, ex: postgres"
  password: "PostgreSQL database password"


categories:
  - EXCHANGE
  - MINING
  - GAMBLING
  - PONZI
  - INDIVIDUAL
  - RANSOMWARE
  - BET


model:
  name: GIN
  args:
    hidden_channels: 256
    dropout: 0.1
    act: relu

learning:

  train_test_split:
    prop_val: 0.3
    prop_test: 0.3
    max_nodes: null
    seed: 0

  init_learning_rate: 0.0001
  max_num_epochs: 2000
  batch_size: 32
  min_num_samples: 300
  max_num_samples: 1500

  resampling_period: 100
  reload_best: false

  lr_scheduler:
    factor: 0.3
    patience: 1000000
    min_lr: 0.

  early_stopping:
    patience: 50

sampling:
  num_neighbors:
    - 10
    - 5
  n_jobs: 12

buffer:
  folder: "buffer-12-n-10-5"
  size: 12

global_seed: 0